name: API-Test

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test_api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: HTTP Request Action
        uses: fjogeleit/http-request-action@v1.9.2
        with:
          url: 'https://fhburgenlandar.my.tricentis.com/default/_e2g/api/flowExecutions'
          method: 'POST'          
          customHeaders: '{"Content-Type": "application/json"}'
          bearerToken: ${{ secrets.E2G_BEARER }}
          data: '{"flowId": "00b7fbd9-880c-4c05-bd66-b511dbbd90ff", "timeoutInMinutes": 5, "priority": 0}'
