name: API-Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: HTTP Request Action
        uses: fjogeleit/http-request-action@v1.9.2
        with:
          url: 'https://fhburgenlandar.my.tricentis.com/default/_e2g/api/flowExecutions'
          method: 'POST'          
          customHeaders: '{"Content-Type": "application/json"}'
          bearerToken: ${{ secrets.E2G_BEARER }}
          data: '{"flowId": "00b7fbd9-880c-4c05-bd66-b511dbbd90ff", "timeoutInMinutes": 5, "priority": 0}'
